Don't commit generated files
vzhou842/generals-bot-cpp pull request #1
Opened 2019-04-24 16:09 UTC by limitedAtonement

2019-04-24 16:13 UTC, vzhou842 requested changes
Should also add Makefile to `.gitignore`

2019-04-24 16:19 UTC, limitedAtonement commented
Absolutely!

2020-11-16 22:39 UTC, limitedAtonement commented
Does that look right?

2020-11-16 22:51 UTC, vzhou842 commented
wow this is pretty old, yeah looks fine

2020-11-16 22:51 UTC, merged